Add launchpad (Closes #133)
wp-media/rocket-lazy-load pull request #134
Opened 2024-05-17 15:07 UTC by nicomollet

Draft PR

2024-05-21 15:51 UTC, nicomollet commented
@CrochetFeve0251 Can you tell why the framework looks loaded twice?
I see the admin menu page twice

![image](https://github.com/wp-media/rocket-lazy-load/assets/108828/38306e84-16fa-414b-9c3f-e2050b194278)

2024-07-01 12:12 UTC, CrochetFeve0251 commented
> @CrochetFeve0251 Can you tell why the framework looks loaded twice? I see the admin menu page twice
> 
> ![image](https://private-user-images.githubusercontent.com/108828/332494059-38306e84-16fa-414b-9c3f-e2050b194278.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MzYxOTEsIm5iZiI6MTcxOTgzNTg5MSwicGF0aCI6Ii8xMDg4MjgvMzMyNDk0MDU5LTM4MzA2ZTg0LTE2ZmEtNDE0Yi05YzNmLWUyMDUwYjE5NDI3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQxMjExMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDJjMDNkN2M3YTA1YzY2MzY1OGRjMmY4MDEzZjljNmZmOGU0ODE3MmZhNmM5NDFmZjRkZjRkY2RlOGI2Y2I0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AE7xSCzUOplHPaYcTcuxL-8clnTSuXHHZQHxjj9XZHc)

@nicomollet the issue with the above code is that you included a subscriber twice.

2024-07-01 12:27 UTC, nicomollet commented
Sure I will look into it @CrochetFeve0251

2024-07-02 21:20 UTC, CrochetFeve0251 requested changes

2024-07-02 21:20 UTC, CrochetFeve0251 commented on src/Admin/AdminPage.php
> +    private string $template_path;
@nicomollet I think this typing wasn't available in php 7.3

2024-07-02 21:20 UTC, CrochetFeve0251 commented on src/Subscriber/AdminPageSubscriber.php
> +	private static string $plugin_basename;
Same here for the type

2024-07-02 21:20 UTC, CrochetFeve0251 commented on src/EventManagement/SubscriberInterface.php
> +    public static function get_subscribed_events();
Maybe https://github.com/wp-launchpad/core/blob/develop/inc/EventManagement/ClassicSubscriberInterface.php is more appropriate for this use case?

2024-07-02 21:20 UTC, CrochetFeve0251 commented on src/Subscriber/AdminPageSubscriber.php
> +			"plugin_action_links_".self::$plugin_basename => 'addPluginPageLink',
I am not sure this is working

2024-07-03 09:23 UTC, nicomollet commented
Tested with PHP:
- `7.3`
- `7.4`
- `8.0`
- `8.1`
- `8.2`

2024-07-04 07:18 UTC, CrochetFeve0251 approved these changes

2024-07-04 12:24 UTC, merged